import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub
} from "react-icons/ai";
import Image from "next/image";
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';

import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';

import {useState} from "react";




export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Abhijeet Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
      <section className='  min-h-screen'>
        <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl font-burtons'>Portfolio</h1>
            <ul className=' flex items-center'>
              <li>
                <BsFillMoonStarsFill 
                onClick={() => setDarkMode(!darkMode)}
                className='cursor-pointer text-2xl'/>
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
            </ul>
        </nav>
        <div className=' text-center p-10'>
          <h2 className=' text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Kumar Abhijeet</h2>
          <h3 className=' text-2xl py-2 md:text-3xl'>Developer and Designer.</h3>
          <p className=' text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto'>
            Enthusiast learner and implementer in the field of web3 development and blockchain DAPPS developer. 
            Looking forward for the opportunity to showcase the knowledge and
            learning got under the same field.
          </p>
        </div>
        <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
          <AiFillTwitterCircle />
          <AiFillLinkedin />
          <AiFillYoutube />
          <AiFillGithub />
        </div>
        <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
          <Image src={deved} layout="fill" objectFit='cover'/>
        </div>
      </section>

      <section>
      <div>
        <h3 className='text-3xl py-1'>Experiences I have gained</h3>
        <p className=' text-md py-5 leading-8 text-gray-800'>
          Since the beginning of my journey from academics, certifications to the corporate IT sector experience
          as designer and developer. I've enhanced my learning with multiple <span className='text-teal-500'> hands on sessions</span> and working on multiple 
          <span className=' text-teal-500'> projects.</span> Got lucky with really great guides and teammates giving challenges and keeping me motivated at each and every step.
        </p>
      </div>
        <div className='lg:flex gap-10'>
          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <center>
              <Image src={design} width={100} height={100} justify-center></Image>
              </center>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>
                Creating elegant designs
              </p>
              <h4 className='py-4 text-teal-600'>Tools Used</h4>
              <p className='text-gray-800 py-1'>HTML</p>
              <p className='text-gray-800 py-1'>CSS</p>
              <p className='text-gray-800 py-1'>MySql</p>
              <p className='text-gray-800 py-1'>JavaScript</p>
            </div>


          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <center>
            <Image src={code} width={100} height={100} justify-center></Image>
            </center>
            <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
            <p className='py-2'>
              Creatimg elegant designs
            </p>
            <h4 className='py-4 text-teal-600'>Tools Used</h4>
            <p className='text-gray-800 py-1'>HTML</p>
            <p className='text-gray-800 py-1'>CSS</p>
            <p className='text-gray-800 py-1'>MySql</p>
            <p className='text-gray-800 py-1'>JavaScript</p>
          </div>

          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <center>
            <Image src={consulting} width={100} height={100} justify-center></Image>
            </center>
            <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
            <p className='py-2'>
              Creatimg elegant designs
            </p>
            <h4 className='py-4 text-teal-600'>Tools Used</h4>
            <p className='text-gray-800 py-1'>HTML</p>
            <p className='text-gray-800 py-1'>CSS</p>
            <p className='text-gray-800 py-1'>MySql</p>
            <p className='text-gray-800 py-1'>JavaScript</p>
          </div>
        </div>
      </section>

      <section>
      <div>
      <h3 className='text-3xl py-1'>Projects</h3>
      <p className=' text-md py-5 leading-8 text-gray-800'>
          Since the beginning of my journey from academics, certifications to the corporate IT sector experience
          as designer and developer. I've enhanced my learning with multiple <span className='text-teal-500'> hands on sessions</span> and working on multiple 
          <span className=' text-teal-500'> projects.</span> Got lucky with really great guides and teammates giving challenges and keeping me motivated at each and every step.
      </p>
      </div>
     
     <div className=' flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
      <div className='basis-1/3 flex-1 rounded-lg object-cover'>
        <Image src={web1} width={'100%'} height={'100%'} layout="responsive"/>
      </div>
      <div className='basis-1/3 flex-1 rounded-lg object-cover'>
        <Image src={web2} width={'100%'} height={'100%'} layout="responsive"/>
      </div>
      <div className='basis-1/3 flex-1 rounded-lg object-cover'>
        <Image src={web3} width={'100%'} height={'100%'} layout="responsive"/>
      </div>
      <div className='basis-1/3 flex-1 rounded-lg object-cover'>
        <Image src={web4} width={'100%'} height={'100%'} layout="responsive"/>
      </div>
      <div className='basis-1/3 flex-1 rounded-lg object-cover'>
        <Image src={web5} width={'100%'} height={'100%'} layout="responsive"/>
      </div>
      <div className='basis-1/3 flex-1 rounded-lg object-cover'>
        <Image src={web6} width={'100%'} height={'100%'} layout="responsive"/>
      </div>

     </div>
     </section> 
        
      </main>

    </div>
  )
}
